### ISSUE TITLE
Rules for sorting Area Tags

### ISSUE THREAD

**Issue by ilm024** [giellalt/lang-smj#1]
Many entries in stems files have an Area tag and are going to a lexicon with additional area tags, giving different inflection. 

For example:

```
eksperimentierit+Area/NO:eks^periment BRILJERE_IV ; ! LOAN 
eksperimentierit+Area/SE:ex^periment BRILJERE_IV ; ! LOAN 

LEXICON BRILJERE_IV_INFL !!= @CODE@
            +Area/NO:ieri%>      DULLUTStem          ;
            +Area/NO:ieri        DeverbalVerbsOADDÁT ;
 +Area/NO+Use/-Spell:ieri        SG3PASS             ;
       +Area/NO+Cond:%>»ierilulu V-ODD-PRET          ;
            +Area/SE:eri%>       DULLUTStem          ;
            +Area/SE:eri         DeverbalVerbsOADDÁT ;
 +Area/SE+Use/-Spell:eri         SG3PASS             ;
       +Area/SE+Cond:%>»erilulu  V-ODD-PRET          ;
```

If one assimilates the word from swedish it will be "eXperimentErit", from norwegian it will assimilate "eKSperimentIErit". Now we are also generating "eXperimentIErit", which is very unlikely, and something we shouldn't suggest.

With the verbs we have had two separate lemmas, going to two different lexicons: eksperimentierit BRILJERE_NOR and experimenterit BRIJLERE_SE. With nouns we have one lemma with area tag going to one lexicon with additional area tags (as example above). 

It's best to have the "one lemma and one lexicon" system, so we need some additional system that somehow sorts doble tags and only generates the area tag that is similar to the area tag the entry has. So that if an entry has an area tag, the system searches the lexicon for similar area tag and generates only this. The Area tag that doesn't correspond to the Area tag i stems file should get `+Use/NG tag`.

**Comment by snomos** [comment]
See followup discussions in [Zulip](https://giella.zulipchat.com/#narrow/stream/124581-smj/topic/lang-smj.20.2F.20Issue.20.231.20Rules.20for.20sorting.20Area.20Tags).

The main reason such mixed forms have not been removed earlier is probably because they should be removed anyway in the area specific fst's. The idea has been that we want to have different spell checker for Norway and Sweden, to make them more targeted and thus better. This is implemented such that all strings from the non-target area is removed from the fst. And that includes mixed forms.

Alas, the area tagging has been inconsistent and covered other things such as dialect variation. The end result has been that the area specific spellers have not been used at all so far, because they did more bad than good.

I will add a filter to remove forms as the above, but only for normative fst's. This way we can analyse misspellings caused by mixing spelling conventions from both majority languages. This can also be used by the grammar checker.

**Comment by snomos** [comment]
And just to prove that it has been fixed:

```sh
# Swedish spelling:
echo experimenterit | hfst-lookup -q analyser-gt-norm.hfstol 
experimenterit	eksperimentierit+V+IV+Inf	0,000000
experimenterit	eksperimentierit+V+IV+Der/d+V+Ind+Prs+Sg3	0,000000

# Mixed area spelling:
echo experimentierit | hfst-lookup -q analyser-gt-norm.hfstol
experimentierit	experimentierit+?	inf

# Norwegian spelling
echo eksperimentierit | hfst-lookup -q analyser-gt-norm.hfstol
eksperimentierit	eksperimentierit+V+IV+Inf	0,000000
eksperimentierit	eksperimentierit+V+IV+Der/d+V+Ind+Prs+Sg3	0,000000
```

**Comment by snomos** [comment]
Problemet som førde til gjenopning:

```
semænnta+N+Sg+Nom: [semænnta, semännta, cemænnta, cemännta]
```

Vi vil ha:

```
semænnta+N+Sg+Nom: [semænnta, cemännta]
```

Problemet her kan vera det at æ/ä-vekslinga skjer i twolc, og dermed fell utanfor taggesystemet.

**Comment by ilm024** [comment]
The new script should also stop our system from generating "æ" for entries with Araa/SE tag and "ä" for entries with Area/NO tag.

semænnta+Area/NO+Sem/Mat:sem PATÆNNTA ; ! GG
semænnta+Area/SE+Sem/Mat:cem PATÆNNTA ;

Now we generate:
semænnta+N+Sg+Nom: [semænnta, semännta, cemænnta, cemännta]

But we only want: 
semænnta+N+Sg+Nom: [semænnta, cemännta]

It's very unlikely that someone would write "cemænnta". It's more likely that someone would write "semännta",  but we shouldn't generate this either.

**Comment by snomos** [comment]
The lexical entries of these words are:

```
semænnta+Area/NO+Sem/Mat:sem PATÆNNTA ; ! GG
semænnta+Area/SE+Sem/Mat:cem PATÆNNTA ;
```

And the `PATÆNNTA` lexicon looks like the following:

```
LEXICON PATÆNNTA
 +N+OLang/NOB: PATÆNNTA_CMP_INFL ;

LEXICON PATÆNNTA_CMP_INFL !!= @CODE@ Recent loanwords on -ænnta with long and short compound-form. The -ennta form (used in "Ådå testamennta") is taged as sub (e always becomes æ in grade three).
 +CmpNP/Pref:ent%>      R                    ;
            :ænnta      MUORRAInfl           ;
            :ænnta      MUORRACmp            ;
   +Err/Orth:ennta      MUORRAInfl           ; !not possible with e in 3.grade!
   +Err/Orth:ennta      MUORRACmp            ;     
   +Err/Orth:enta       A_CMP_INFL           ; ! makes old patenta
```

That is, all entries get Norwegian `æ`, which in turn is optionally made into `ä` in twolc - with no tag whatsoever. Thus we get both forms independent of any tags.
