### ISSUE TITLE
Komparativ som grunnform for 46 OANEP-ord? (

### ISSUE THREAD

**Issue by albbas** [giellalt/lang-smj#101]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2004
Date: 2015-03-02T22:03:18+01:00
From: Trond Trosterud &lt;<trond.trosterud>&gt;
To:   Elena Junie Paulsen &lt;<elena.j.paulsen>&gt;
CC:   lene.antonsen, maja.l.kappfjell, sjur.n.moshagen, thomas.omma, trond.trosterud

Last updated: 2019-10-02T00:56:58+02:00

**Comment by albbas** [comment]
## Comment 10295
Date: 2015-03-02 23:11:25 +0100
From: Lene Antonsen &lt;<lene.antonsen>&gt;

I sme har vi gjort slik med substantiver som gradbøyes som adjektiver, og som blir adverber:

gáttit
gáttit	gáddi+N+Der/A+A+Comp+Attr
gáttit	gáddi+N+Der/A+A+Comp+Sg+Nom
gáttit	gáddi+N+Der/A+A+Der/at+Adv


nuorttat
nuorttat	nuorta+N+Der/A+A+Comp+Attr
nuorttat	nuorta+N+Der/A+A+Comp+Sg+Nom
nuorttat	nuorta+N+Der/A+A+Der/at+Adv

**Comment by albbas** [comment]
## Comment 10296
Date: 2015-03-03 11:48:32 +0100
From: Sandra Nystø Rahka &lt;<sandra.rahka>&gt;

I tillegg til OANEP finnes det 3 leksikoner til med komparativ og superlativ som grunnform. Mange er adjektiv som allerede finnes oppført med en positiv grunnform og dermed får vi en dobbeltform. Hvorfor disse har havnet i disse leksikonene vet jeg ikke, men de bør tas bort derfra. 

Noen av disse er adjektiver som er mer eller mindre leksikaliserte i komparativ og/eller superlativ form, som f.eks:

sisŋep
sisŋep	sisŋep+A+Comp+Attr
sisŋep	sisŋep+A+Comp+Sg+Nom

sisŋemus
sisŋemus	sisŋep+A+Superl+Attr
sisŋemus	sisŋep+A+Superl+Sg+Nom

Finner ingen tilsvarende postitiv form i verken Korhonen eller Kintel (Har ikke Spiik her).  

Når det gjelder gradbøying av N, så er det noen, og da stedssubstantiver, som kan gradbøyes. Disse hører til leksikon ÅLGGO i nouns.lexc:

vuolep	vuolle+N+Comp+Attr
vuolep	vuolle+N+Comp+Sg+Nom

lulep	lulle+N+Comp+Attr
lulep	lulle+N+Comp+Sg+Nom

Dette er også tilfellet med de ordene som er analyserte som postposisjonene og adverbene som finnes i komparativ og/eller superlativ form. Disse betegner også sted og kan derfor kompareres. 

oarjjela
oarjjela	oarjjela+Adv
oarjjela	oarjjela+Po
oarjjela	oarjjela+Pr

oarjjelabbo	oarjjelabbo+A+Comp+Sg+Nom

Faktisk så bør det vurderes om ikke slike -el(a)-ord burde analyseres som substantiv i stedet da de funker som vanlige substantiv generelt med kasusbøyning, og som stedsubstantiver spesielt med gradbøying. Guovddel er for eksempel allerede analysert som substantiv i tillegg til som postposisjon:

guovddel	guovddel+N+Sg+Nom

guovddela
guovddela	guovddel+N+Pl+Nom
guovddela	guovddel+N+Sg+Gen

guovddelav
guovddelav	guovddel+N+Sg+Acc
guovddelav	guovddelav+Adv
guovddelav	guovddelav+Po

guovddelij
guovddelij	guovddel+N+Pl+Gen
guovddelij	guovddel+N+Pl+Com
guovddelij	guovddel+N+Sg+Ill
guovddelij	guovddelij+Adv
guovddelij	guovddelij+Po

guovddelin
guovddelin	guovddel+N+Ess
guovddelin	guovddel+N+Sg+Ine
guovddelin	guovddelin+Adv
guovddelin	guovddelin+Po
guovddelin	guovddelin+Pr

guovddelis
guovddelis	guovddelis+N+Sg+Nom
guovddelis	guovddel+N+Sg+Ela

guovddelis	guovddelis+Adv
guovddelis	guovddelis+Po

guovddelijn
guovddelijn	guovddel+N+Pl+Ine
guovddelijn	guovddel+N+Sg+Com

I det hele tatt bør det ryddes litt opp i adjektivfila. Er enig i at positiv skal være lemma, men for de nevnte leksikaliserte komparativ- og superlativformene lar dette seg vanskelig gjøre. Vi gradbøyer A, men også i tillegg en viss type N (som er oppførte i ÅLGGO lex og en evt GUOVDDEL lex). 

Utover det er adverb avledet fra adjektiv allerede i adverbfila. Substantiver som gradbøyes kan avledes til adverb lik vanlige adjektiv: 

nuortap+A+Comp+Der/at+Adv	nuortabut

Substantiv som gradbøyes, f.eks nuortta -> nuortap, kan derfor ikke analyseres som adverb

**Comment by albbas** [comment]
## Comment 10298
Date: 2015-03-03 13:18:33 +0100
From: Sandra Nystø Rahka &lt;<sandra.rahka>&gt;

"Sån guovddelav davás manná"
"Vatte guovddelij"
"Sån guovddelin vuodjá"

Det er klart at rent syntaktisk får de en adverbanalyse. Og de bør nok fortsatt å ha en postposisjon/adverbanalyse også morfologisk, men ved å i tillegg analysere dem som substantiver så får vi ryddet en del opp i disse "inherent comparatives and superlatives" leksikonene.

**Comment by albbas** [comment]
## Comment 10299
Date: 2015-03-03 13:28:41 +0100
From: Lene Antonsen &lt;<lene.antonsen>&gt;

Jeg foreslår at vi tar en felles diskusjon for sme sma og smj om disse og bli enige om en strategi. Hvis det ikke er gode grunner for det, bør vi ikke ha forskjellige løsninger for hvert språk.

**Comment by albbas** [comment]
## Comment 10303
Date: 2015-03-04 22:47:41 +0100
From: Trond Trosterud &lt;<trond.trosterud>&gt;

Eg er samd -- neste veke?  No har vi også fine nye korp-versjonar med betre grunnlag for å sjå kva som skjer i korpus (men det meste av diskusjonen gjeld konseptuelle meir enn empiriske ting)

**Comment by albbas** [comment]
## Comment 10309
Date: 2015-03-05 10:43:37 +0100
From: Sandra Nystø Rahka &lt;<sandra.rahka>&gt;

Foreslår at vi tar det uka etter, når det er Divvun-samling i Tromsø

**Comment by albbas** [comment]
## Comment 12881
Date: 2018-05-25 20:34:37 +0200
From: Trond Trosterud &lt;<trond.trosterud>&gt;

Denne diskusjonen drukna visst i 2015.  Kanskje vi berre skal seie at vi endrar alle komparative lemma til positiv? (for eit par er det gjort allereie.

davep   davve+N+Comp+Attr
davep   davve+N+Comp+Sg+Nom
davep   davep+A+Comp+Attr
davep   davep+A+Comp+Sg+Nom

dibbmáp dibbmáp+A+Comp+Attr
dibbmáp dibbmáp+A+Comp+Sg+Nom

divrráp divrráp+A+Comp+Attr
divrráp divrráp+A+Comp+Sg+Nom
...

**Comment by albbas** [comment]
## Comment 13710
Date: 2019-10-02 00:56:58 +0200
From: Sjur Nørstebø Moshagen &lt;<sjur.n.moshagen>&gt;

Flytta frå Sandra til Elena.

**Comment by ilm024** [comment]
Jeg har fjernet de resterende komparative adjektivene som kunne fjernes, altså de som har en mulig positiv eller som har grunnform som substantiv. 

Resterende må bare være i OANEP, vi kan muligens legge til +Gram/Comp tag. @leneantonsen @Trondtr
