### ISSUE TITLE
North sámi testdata in SMJ

### ISSUE THREAD

**Issue by ilm024** [giellalt/lang-smj#103]
SMJ make check is failing:

```
FAIL: accept-all-lemmas.sh
============================================================================
Testsuite summary for Giella smj 0.2.0
============================================================================
# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See tools/spellcheckers/test/fstbased/desktop/hfst/test-suite.log
Please report to feedback@divvun.no
```

It seams like it north sámi test data in SMJ:

```
=====================================================================================
   Giella smj 0.2.0: tools/spellcheckers/test/fstbased/desktop/hfst/test-suite.log
=====================================================================================

# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: accept-all-lemmas.sh
==========================

"Áváhårsa" is NOT in the lexicon:
"Helmuk" is NOT in the lexicon:
"Kr.å" is NOT in the lexicon:
"Kr.m" is NOT in the lexicon:
"Mančuria" is NOT in the lexicon:
"MuVá" is NOT in the lexicon:
"Tearbmasymposia" is NOT in the lexicon:
"Vuottnánáhpe" is NOT in the lexicon:
"áhpeguollebivdár" is NOT in the lexicon:
"álggididdje" is NOT in the lexicon:
see rejected_lemmas.txt for more
FAIL accept-all-lemmas.sh (exit status: 1)
```

**Comment by ilm024** [comment]
> ```
> "færtguhti" is NOT in the lexicon:
> "goabbák guojmme" is NOT in the lexicon:
> "guhtik guojmme" is NOT in the lexicon:
> "guoktajuodevidálågåk" is NOT in the lexicon:
> "guoktajuohtevidálågåk" is NOT in the lexicon:
> "iesjguhti" is NOT in the lexicon:
> "lågenan" is NOT in the lexicon:
> "nubbe nubbe" is NOT in the lexicon:
> ```


"færtguhti" is NOT in the lexicon:> not a word, maybe "færtguhtik"
"guoktajuodevidálågåk" is NOT in the lexicon: > typo in test? "guoktatjuodevidálågåk"
"guoktajuohtevidálågåk" is NOT in the lexicon: > typo in test? "guoktatjuohtevidálågåk"
"iesjguhti" is NOT in the lexicon: > not a word, maybe "iesjguhtik"
"lågenan" is NOT in the lexicon: > not a word, works only as cmp

I don't know what to do with MWE:
"nubbe nubbe" is NOT in the lexicon:
"goabbák guojmme" is NOT in the lexicon:
"guhtik guojmme" is NOT in the lexicon:

**Comment by flammie** [comment]
> > ```
> > "færtguhti" is NOT in the lexicon:
> > "goabbák guojmme" is NOT in the lexicon:
> > "guhtik guojmme" is NOT in the lexicon:
> > "guoktajuodevidálågåk" is NOT in the lexicon:
> > "guoktajuohtevidálågåk" is NOT in the lexicon:
> > "iesjguhti" is NOT in the lexicon:
> > "lågenan" is NOT in the lexicon:
> > "nubbe nubbe" is NOT in the lexicon:
> > ```
> 
> "færtguhti" is NOT in the lexicon:> not a word, maybe "færtguhtik" 
> "guoktajuodevidálågåk" is NOT in the lexicon: > typo in test?  "guoktatjuodevidálågåk"
> "guoktajuohtevidálågåk" is NOT in the lexicon: > typo in test? "guoktatjuohtevidálågåk"
> "iesjguhti" is NOT in the lexicon: > not a word, maybe "iesjguhtik"

these might be typoes in lexc files? I.e. https://github.com/giellalt/lang-smj/blob/main/src/fst/morphology/stems/pronouns.lexc#L354-L366 https://github.com/giellalt/lang-smj/blob/main/src/fst/morphology/stems/pronouns.lexc#L433-L449 and https://github.com/giellalt/lang-smj/blob/main/src/fst/morphology/stems/numerals.lexc#L643-L650

>  "lågenan" is NOT in the lexicon: > not a word, works only as cmp
> I don't know what to do with MWE: "nubbe nubbe" is NOT in the lexicon: "goabbák guojmme" is NOT in the lexicon: "guhtik guojmme" is NOT in the lexicon:

mm, for now we can manually filter them from testing, I'll use `! NOT-TO-LEMMATEST` in lexc comments for this. Naturally the abovementioned can be excluded with same method if its relevant.

**Comment by flammie** [comment]
> > I'm thinking we can exclude +Err/Der and ab-dot and VINJO- from testing?
> 
> By default everything containing `+Err/` should be removed from testing, so if it is not, that is a bug that needs to be investigated. 

That might be a good option, the current template only has: `--exclude "(CmpN/Only|ShCmp|\+Cmp\/SplitR| Rreal | R | Rnoun |\+V\+|NOT-TO-LEMMATEST)"` although notably fixing it won't be applied the most developed language since this line is modified in all languages.

**Comment by snomos** [comment]
> > > I'm thinking we can exclude +Err/Der and ab-dot and VINJO- from testing?
> > 
> > 
> > By default everything containing `+Err/` should be removed from testing, so if it is not, that is a bug that needs to be investigated.
> 
> That might be a good option, the current template only has: `--exclude "(CmpN/Only|ShCmp|\+Cmp\/SplitR| Rreal | R | Rnoun |\+V\+|NOT-TO-LEMMATEST)"` although notably fixing it won't be applied the most developed language since this line is modified in all languages.

I see now that the relevant line in the extract lemma script is not as thorough as it should be regarding noise:

https://github.com/giellalt/giella-core/blob/f73fef326ddd9cabdd9e07f28ba5ddf71ca2d960/scripts/extract-lemmas.sh#L96

This should be fixed.

**Comment by snomos** [comment]
> This should be fixed.

Done in https://github.com/giellalt/giella-core/commit/3b766fb8d4628188ef30c25d26a9e9cf1e771cb1
