### ISSUE TITLE
Legg til manglande ordklassetaggar til smj-abbreviations.lexc

### ISSUE THREAD

**Issue by snomos** [giellalt/lang-smj#13]
Jf [smj-abbreviations.lexc](https://github.com/giellalt/lang-smj/blob/main/src/fst/stems/smj-abbreviations.lexc), både `N` og `O` og mange fleire manglar ordklassetagg.

**Comment by ilm024** [comment]
uit-mac-219:lang-smj ilm024$ svn ci -m "la til ordklassetag, issue #13" src/fst/stems/smj-abbreviations.lexc 
Sending        src/fst/stems/smj-abbreviations.lexc
Transmitting file data .done
Committing transaction...
Committed revision 19038.
