### ISSUE TITLE
Segmentera samansette bindestreksord med kjende delar

### ISSUE THREAD

**Issue by snomos** [giellalt/lang-smj#17]
Etter at @flammie fiksa #16 (takk - det var ein dum feil eg hadde gjort 😮 ) så er vi tilbake til utgangspunktet:

```sh
echo "tyska-giellaj" | hfst-tokenise -g tools/tokenisers/tokeniser-tts-cggt-desc.pmhfst 
"<tyska-giellaj>"
	"tyska-giellaj" ?
:\n
```

Det eg gjerne skulle ha fått til er å nytta `@PMATCH_BACKTRACKING@` til å dela opp ordet i ulike bitar, i dei tilfella der enkeltdelar er analyserbare, som t.d. `giellaj` i dømet over:

```sh
echo "giellaj" | hfst-tokenise -g tools/tokenisers/tokeniser-tts-cggt-desc.pmhfst 
"<giellaj>"
	"giella" N Sem/Lang_Tool-catch Sg Ill <W:0.0>
:\n
```

I pmatch-fila er `inputmark` definert slik:

```
Define inputmark    [ 0:"@PMATCH_INPUT_MARK@" | 0:"@PMATCH_BACKTRACKING@" ];
```

Og eg har endra `alphaword` slik:

```
Define alphaword alphabet+ ( alphamiddle ( inputmark ) alphabet+ );
```

Likevel får eg ikkje `hfst-tokenise` til å dela opp ordet i ulike delar, med kvar sin analyse. Har de forslag, @unhammer og @flammie ?

**Comment by snomos** [comment]
Eg prøvde å gjera `inputmark` obligatorisk, slik:

```
Define alphaword alphabet+ ( alphamiddle inputmark alphabet+ );
```

Men det hjelpte ikkje.

Det eg er ute etter er altså å få alternative segmenteringar av ord som inneheld klare delingspunkt (t.d. bindestrek), som ei alternativ segmentering til heile ordet. Dvs at i dømet over vil eg gjerne ha ut dette:

```sh
echo "tyska-giellaj" | hfst-tokenise -g tools/tokenisers/tokeniser-tts-cggt-desc.pmhfst 
"<tyska-giellaj>"
	"tyska-giellaj" ?
	"giella" N Sem/Lang_Tool-catch Sg Ill <W:0.0>
		"tyska-" ?
:\n
```

Er det mogleg?

**Comment by unhammer** [comment]
Kanskje dumt spørsmål, men går det ikkje an å løysa dette i leksikonet på «vanleg» måte med sti frå bindestrek til rot av substantivleksikonet? (Slike løysingar pleiar iallfall å vera litt enklare å debugga, når dei er moglege.)

**Comment by snomos** [comment]
Om eg forstår deg rett så føreset det at `tyska` ligg i leksikonet. Men det eg vil ha er ei løysing som fungerer for *ukjende* ord + bindestrekssamansetjing (`tyska` er ein skrivefeil for `dujska`).

**Comment by snomos** [comment]
Nesten der, og mykje enklare:

```sh
echo "tyska-giellaj" | hfst-tokenise -g tools/tokenisers/tokeniser-tts-cggt-desc.pmhfst
:tysk
"<a->"
	"a" N Sem/Sign ABBR Gram/TAbbr Cmp/SplitR Cmp <W:0.0>
"<giellaj>"
	"giella" N Sem/Lang_Tool-catch Sg Ill <W:0.0>
:\n
```
