### ISSUE TITLE
Problem med bindestrekssamansetjing i tts-segmenteringa

### ISSUE THREAD

**Issue by snomos** [giellalt/lang-smj#18]
Jf:

```sh
echo "tæksta" | hfst-lookup -q src/analyser-tts-gt-input.hfstol \
| cut -f2 \
| hfst-lookup -q src/analyser-tts-gt-output.hfstol 
tæksta>	tæksta+Area/NO+N+Sem/Txt+Sg+Nom
tæksta>	tæksta+Area/SE+N+Sem/Txt+Sg+Nom

	+?	inf

echo "tæksta" | hfst-tokenise -g tools/tokenisers/tokeniser-tts-cggt-desc.pmhfst 
"<tæksta>"
	"tæksta" ?
:\n
```

Analysatoren er delt i to for å kunna skapa ein feik-treteip-analysator, slik at vi har mellomnivået tilgjengeleg for vidare prosessering. Mellomnivået med synlege flagg ser slik ut:

```sh
echo "tæksta" \
| hfst-lookup -q -X show-flags src/analyser-tts-gt-input.hfstol 

tæksta	@P.Px.add@tæ@U.Area.NO@ksta>@D.CmpOnly.FALSE@@D.CmpPref.TRUE@@D.NeedNoun.ON@

echo "tæksta" \
| hfst-lookup -q src/analyser-tts-gt-input.hfstol \
| cut -f2 \
| hfst-lookup -q -X show-flags src/analyser-tts-gt-output.hfstol 

tæksta>	@P.Px.add@tæ@U.Area.NO@ksta+Area/NO@U.Area.NO@+N+Sem/Txt+Sg+Nom@D.CmpOnly.FALSE@@D.CmpPref.TRUE@@D.NeedNoun.ON@
tæksta>	@P.Px.add@tæ@U.Area.SE@ksta+Area/SE@U.Area.SE@+N+Sem/Txt+Sg+Nom@D.CmpOnly.FALSE@@D.CmpPref.TRUE@@D.NeedNoun.ON@

	+?	inf

echo tæksta+Area/NO+N+Sem/Txt+Sg+Nom \
| hfst-flookup -q -X show-flags src/analyser-tts-gt-output.hfst

tæksta+Area/NO+N+Sem/Txt+Sg+Nom	@P.Px.add@tæ@U.Area.NO@ksta@U.Area.NO@>@D.CmpOnly.FALSE@@D.CmpPref.TRUE@@D.NeedNoun.ON@
```

Eg ser ein einaste skilnad: Det er ein ekstra `@U.Area.NO@` før `>` i `analyser-tts-gt-output.hfst` - kan det vera grunnen til manglande analyse med `hfst-tokenise`, @flammie ?

**Comment by snomos** [comment]
Det fungerer for enkle ord, men ikkje for samansetjingar, difor gjenopna:

```sh
echo tæksta | hfst-tokenise -g tools/tokenisers/tokeniser-tts-cggt-desc.pmhfst 
"<tæksta>"
	"tæksta" Area/NO N Sem/Txt Sg Nom <W:0.0>
:\n

echo täksta | hfst-tokenise -g tools/tokenisers/tokeniser-tts-cggt-desc.pmhfst 
"<täksta>"
	"tæksta" Area/NO N Sem/Txt Sg Nom <W:0.0>
	"tæksta" Area/SE N Sem/Txt Sg Nom <W:0.0>
:\n

echo tæksta-TV | hfst-tokenise -g tools/tokenisers/tokeniser-tts-cggt-desc.pmhfst 
"<tæksta-TV>"
	"tæksta-TV" ?
:\n

echo täksta-TV | hfst-tokenise -g tools/tokenisers/tokeniser-tts-cggt-desc.pmhfst 
"<täksta-TV>"
	"täksta-TV" ?
:\n
```

Det er dessutan ein mystisk dobbelt-analyse av `täksta` (svensk `ä`) - han er både norsk og svensk samtidig!

**Comment by snomos** [comment]
Leksikalisert samansetjing:

```sh
echo täksta-TV | hfst-lookup -q -X show-flags src/analyser-tts-gt-input.hfst
täksta-TV	tæ@U.Area.SE@ksta@P.Pmatch.Backtrack@-@P.Pmatch.Backtrack@TV@U.Area.SE@

vs:

echo tæksta-TV+Area/SE+N+Sem/Org_Prod-vis+ACR+Sg+Nom \
| hfst-flookup -q -X show-flags src/analyser-tts-gt-output.hfst
tæksta-TV+Area/SE+N+Sem/Org_Prod-vis+ACR+Sg+Nom	tæ@U.Area.SE@ksta@P.Pmatch.Backtrack@-@P.Pmatch.Backtrack@TV@U.Area.SE@
```

Det er symbolidentitet der fst-ane møtest etter det eg kan sjå.

**Comment by snomos** [comment]
Dynamisk samansetjing:

```sh
echo täksta-TV | hfst-lookup -q -X show-flags src/analyser-tts-gt-input.hfst
täksta-TV	@P.Px.add@tæ@U.Area.SE@ksta@U.Area.SE@>@P.CmpFrst.FALSE@@P.CmpPref.FALSE@@D.CmpLast.TRUE@@D.CmpNone.TRUE@@U.CmpNone.FALSE@@P.CmpOnly.TRUE@@P.Pmatch.Backtrack@-@P.Pmatch.Backtrack@∑#TV@U.Area.SE@

vs

echo tæksta+Area/SE+N+Sem/Txt+Cmp/SgNom+Cmp/Hyph+Cmp#TV+v1+Area/SE+N+Sem/Obj-el+ACR+Sg+Nom | hfst-flookup -q -X show-flags src/analyser-tts-gt-output.hfst
tæksta+Area/SE+N+Sem/Txt+Cmp/SgNom+Cmp/Hyph+Cmp#TV+v1+Area/SE+N+Sem/Obj-el+ACR+Sg+Nom	@P.Px.add@tæ@U.Area.SE@ksta@U.Area.SE@>@P.CmpFrst.FALSE@@P.CmpPref.FALSE@@D.CmpLast.TRUE@@D.CmpNone.TRUE@@U.CmpNone.FALSE@@P.CmpOnly.TRUE@@P.Pmatch.Backtrack@-@P.Pmatch.Backtrack@∑#TV@U.Area.SE@
```

Her òg er det symbolsamsvar der fst-ane møtest.

**Comment by snomos** [comment]
I døma ovanfor har eg fjerna andre analyser for å gjera det lettare å samanlikna. Kan det henda at det finst andre analyser der symbola ikkje stemmer, og at det fører til at alle analyser blir forkasta?

**Comment by flammie** [comment]
Ä har debugga den nå, det synes pmatch finner ingenting i först lookup allerede also den problem står ikke i uncomposition men i lookup av `_relabelled` automata, om ä bruker de automata uten relabelling det fungerer ok (men kanskje uten backtracking og sånn):

```patch
diff --git a/tools/tokenisers/tokeniser-tts-cggt-desc.pmscript b/tools/tokenisers/tokeniser-tts-cggt-desc.pmscript
index 055e01808..ed894012f 100644
--- a/tools/tokenisers/tokeniser-tts-cggt-desc.pmscript
+++ b/tools/tokenisers/tokeniser-tts-cggt-desc.pmscript
@@ -24,8 +24,10 @@
 
 set need-separators off
 
-Define  inputlexmorph @bin"analyser_relabelled-tts-cggt-input.hfst" ;
-Define outputlexmorph @bin"analyser_relabelled-tts-cggt-output.hfst" ;
+! Define  inputlexmorph @bin"analyser_relabelled-tts-cggt-input.hfst" ;
+! Define outputlexmorph @bin"analyser_relabelled-tts-cggt-output.hfst" ;
+Define  inputlexmorph @bin"analyser-tts-cggt-input.hfst" ;
+Define outputlexmorph @bin"analyser-tts-cggt-output.hfst" ;
 
 Define inmorphology [ inputlexmorph | UpCase(inputlexmorph, U) ] ;
 Define outmorphology [ outputlexmorph ] ;
```

```console
$  echo tæksta-tv | hfst-tokenise -g tokeniser-tts-cggt-desc.pmhfst 
"<tæksta-tv>"
	"TV" v2 Area/NO N Sem/Obj-el ACR Pl Nom Err/Orth <W:0.0>
		"tæksta" Area/NO N Sem/Txt Cmp/SgNom Cmp/Hyph Cmp <W:0.0>
	"TV" v2 Area/NO N Sem/Obj-el ACR Sg Gen Err/Orth <W:0.0>
		"tæksta" Area/NO N Sem/Txt Cmp/SgNom Cmp/Hyph Cmp <W:0.0>
	"TV" v2 Area/NO N Sem/Obj-el ACR Sg Nom <W:0.0>
		"tæksta" Area/NO N Sem/Txt Cmp/SgNom Cmp/Hyph Cmp <W:0.0>
	"tæksta-tv" Area/NO N Sem/Org_Prod-vis ACR Pl Nom Err/Orth <W:0.0>
	"tæksta-tv" Area/NO N Sem/Org_Prod-vis ACR Sg Gen Err/Orth <W:0.0>
	"tæksta-tv" Area/NO N Sem/Org_Prod-vis ACR Sg Nom <W:0.0>
:\n
```
kanskje dobbelt backtrack fungerer ikke ennu med tokenise?

**Comment by snomos** [comment]
@unhammer har du synspunkt på kva som kan vera problemet?

**Comment by unhammer** [comment]
Kva gjer relabelling her?

**Comment by snomos** [comment]
> Kva gjer relabelling her?

Eg trudde relabelling var ein føresetnad for fungerande BT og splitting. Stemmer ikkje det?

**Comment by flammie** [comment]
https://github.com/giellalt/giella-core/blob/master/am-shared/tools-tokenisers-dir-include.am#L148 er kjellkod för reballer also det bara erstatter nån flagdiakritiker med nånting pmatch-spesifikk (men nåen som man kan ikke lengre analyse med vanlig lookup tror ä).

**Comment by snomos** [comment]
> https://github.com/giellalt/giella-core/blob/master/am-shared/tools-tokenisers-dir-include.am#L148 er kjellkod för reballer also det bara erstatter nån flagdiakritiker med nånting pmatch-spesifikk (men nåen som man kan ikke lengre analyse med vanlig lookup tror ä).

Jo, eg veit, og det veit @unhammer òg, sidan det var han som laga systemet 🙂 Difor forstår eg ikkje spørsmålet til @unhammer - eg trudde altså at relabelling var eit naudsynt steg for å få backtracking og splitting til å fungera. Som du har demonstrert, @flammie , så fungerer ting utan relabelling. Men fungerer backtracking og splitting som det skal då?

**Comment by unhammer** [comment]
> og det veit @unhammer òg

Nei, du skal ikkje undervurdera mi evne til å gløyma kva eg har gjort. Men viss eg les koden rett så er det relabelling som gjer giella-taggane om til dei faktiske pmatch-symbola. Og som https://github.com/giellalt/lang-smj/issues/18#issuecomment-1067592908 viser så manglar ordformtaggar på den dynamiske samansetjinga – sannsynlegvis fordi det ikkje er nokon `@PMATCH_INPUT_MARK@`. Så utan relabelling blir det ingen backtracking og heller ingen ordform-taggar (uavhengig av backtracking).

**Comment by snomos** [comment]
> Kan du køyra døma i [#18 (comment)](https://github.com/giellalt/lang-smj/issues/18#issuecomment-1064106855) med _relabelled-fst-ane?

```sh
echo täksta-TV | hfst-lookup -q -X show-flags tokenisers/analyser_relabelled-tts-cggt-input.hfst 
täksta-TV	@P.Px.add@tæ@U.Area.NO@ksta@U.Area.NO@>@P.CmpFrst.FALSE@@P.CmpPref.FALSE@@D.CmpLast.TRUE@@D.CmpNone.TRUE@@U.CmpNone.FALSE@@P.CmpOnly.TRUE@@PMATCH_BACKTRACK@@PMATCH_INPUT_MARK@-@PMATCH_BACKTRACK@@PMATCH_INPUT_MARK@∑#TV@U.Area.NO@
täksta-TV	@P.Px.add@tæ@U.Area.SE@ksta@U.Area.SE@>@P.CmpFrst.FALSE@@P.CmpPref.FALSE@@D.CmpLast.TRUE@@D.CmpNone.TRUE@@U.CmpNone.FALSE@@P.CmpOnly.TRUE@@PMATCH_BACKTRACK@@PMATCH_INPUT_MARK@-@PMATCH_BACKTRACK@@PMATCH_INPUT_MARK@∑#TV@U.Area.SE@
täksta-TV	tæ@U.Area.NO@ksta@PMATCH_BACKTRACK@@PMATCH_INPUT_MARK@-@PMATCH_BACKTRACK@@PMATCH_INPUT_MARK@TV@U.Area.NO@
täksta-TV	tæ@U.Area.SE@ksta@PMATCH_BACKTRACK@@PMATCH_INPUT_MARK@-@PMATCH_BACKTRACK@@PMATCH_INPUT_MARK@TV@U.Area.SE@
```

**Comment by snomos** [comment]
```sh
hfst-traverse tokenisers/analyser_relabelled-tts-cggt-output.hfst
Traversing automaton substitute-@P.Pmatch.Loc@-with-net-relabeller.hfst(substitute-@P.Pmatch.Backtrack@-with-net-btrelabeller.hfst(UNNAMED))
```

gjev til slutt dette resultatet:

```
On path `
t:t
æ:æ
@U.Area.SE@:@U.Area.SE@
k:k
s:s
t:t
a:a
@_EPSILON_SYMBOL_@:-
@_EPSILON_SYMBOL_@:@_EPSILON_SYMBOL_@
@_EPSILON_SYMBOL_@:@PMATCH_BACKTRACK@
@_EPSILON_SYMBOL_@:@PMATCH_INPUT_MARK@
@_EPSILON_SYMBOL_@:@_EPSILON_SYMBOL_@
-:@_EPSILON_SYMBOL_@
@_EPSILON_SYMBOL_@:@_EPSILON_SYMBOL_@
@_EPSILON_SYMBOL_@:@PMATCH_BACKTRACK@
@_EPSILON_SYMBOL_@:@PMATCH_INPUT_MARK@
@_EPSILON_SYMBOL_@:@_EPSILON_SYMBOL_@
T:T
V:V
@_EPSILON_SYMBOL_@: Area/SE
@U.Area.SE@:@U.Area.SE@
@_EPSILON_SYMBOL_@: N
@_EPSILON_SYMBOL_@: Sem/Org_Prod-vis
@_EPSILON_SYMBOL_@: ACR
@_EPSILON_SYMBOL_@: Sg
@_EPSILON_SYMBOL_@: Nom
' are continuations:
<Nothing, you've hit a dead end here>
```

**Comment by snomos** [comment]
Her er dei siste analysene med flagga synlege:

```sh
echo "tæksta-TV Area/NO N Sem/Org_Prod-vis ACR Sg Nom" \
| hfst-flookup -q tokenisers/analyser-tts-cggt-output.hfst
tæksta-TV Area/NO N Sem/Org_Prod-vis ACR Sg Nom	tæksta-TV

echo "tæksta-TV Area/NO N Sem/Org_Prod-vis ACR Sg Nom" \
| hfst-flookup -q -X show-flags tokenisers/analyser-tts-cggt-output.hfst
tæksta-TV Area/NO N Sem/Org_Prod-vis ACR Sg Nom	tæ@U.Area.NO@ksta@P.Pmatch.Backtrack@-@P.Pmatch.Backtrack@TV@U.Area.NO@
```

Dvs at eg tok feil tiidlegare då eg sa:

> Dvs at det som output-analysatoren ventar seg er den underliggjande forma av inndata (dvs `tæksta` istf `täksta`), men elles uforandra. Det er ingen spor etter backtracking osb på inndatasida av output-analysatoren.

**Comment by snomos** [comment]
Det ser ut som om relabel-fst-ane berre har BT-symbol på eine sida, med ein epsilon på andre. Kan det stemma? Jf https://github.com/giellalt/giella-core/blob/0b73bf12466f9a1d41aa094f7a07eeb9c847901f/am-shared/tools-tokenisers-dir-include.am#L148-L159, der fst-ane som blir produserte ser slike ut:

```sh
printf '0\t1\t@0@\t@PMATCH_BACKTRACK@\n1\t2\t@0@\t@PMATCH_INPUT_MARK@\n2\n'
0	1	@0@	@PMATCH_BACKTRACK@
1	2	@0@	@PMATCH_INPUT_MARK@
2
printf '0\t1\t@0@\t@PMATCH_INPUT_MARK@\n1\n'
0	1	@0@	@PMATCH_INPUT_MARK@
1
```

Er det dette som er grunnen til at kvasiflagga blir ståande på inndatasida?

**Comment by snomos** [comment]
> Er det dette som er grunnen til at kvasiflagga blir ståande på inndatasida?

Nei, for det er like feil i andre retninga av denne fst-en:

```sh
echo "tæksta-TV" | hfst-lookup -q -X show-flags tokenisers/analyser-tts-cggt-output.hfst                         
tæksta-TV	tæ@U.Area.NO@ksta-@P.Pmatch.Backtrack@@P.Pmatch.Backtrack@TV Area/NO@U.Area.NO@ N Sem/Org_Prod-vis ACR Pl Nom Err/Orth
tæksta-TV	tæ@U.Area.NO@ksta-@P.Pmatch.Backtrack@@P.Pmatch.Backtrack@TV Area/NO@U.Area.NO@ N Sem/Org_Prod-vis ACR Sg Gen Err/Orth
tæksta-TV	tæ@U.Area.NO@ksta-@P.Pmatch.Backtrack@@P.Pmatch.Backtrack@TV Area/NO@U.Area.NO@ N Sem/Org_Prod-vis ACR Sg Nom
tæksta-TV	tæ@U.Area.SE@ksta-@P.Pmatch.Backtrack@@P.Pmatch.Backtrack@TV Area/SE@U.Area.SE@ N Sem/Org_Prod-vis ACR Pl Nom Err/Orth
tæksta-TV	tæ@U.Area.SE@ksta-@P.Pmatch.Backtrack@@P.Pmatch.Backtrack@TV Area/SE@U.Area.SE@ N Sem/Org_Prod-vis ACR Sg Gen Err/Orth
tæksta-TV	tæ@U.Area.SE@ksta-@P.Pmatch.Backtrack@@P.Pmatch.Backtrack@TV Area/SE@U.Area.SE@ N Sem/Org_Prod-vis ACR Sg Nom
```

**Comment by unhammer** [comment]
> relabel-fst-ane berre har BT-symbol på eine sida, med ein epsilon på andre. Kan det stemma?

Make-fila køyrer `hfst-substitute -f '@P.Pmatch.Loc@'  -T  relabeller.hfst`, så om du har ein kant med `@P.Pmatch.Loc@` på begge sider, så blir den til epsilon på form-sida og input-mark på analysesida. Det høyrest rett ut for meg. 

Er forskjellen i dei to analysane at `-` er føre dei to bt-symbola i output, og mellom i input? (Det er vel mellom i lexc?)

**Comment by snomos** [comment]
> Er forskjellen i dei to analysane at `-` er føre dei to bt-symbola i output, og mellom i input? (Det er vel mellom i lexc?)

Ja, det er den einaste skilnaden eg ser. Det merkelege er at før `substitute`-steget så er `-` på rett plass, dvs mellom.

**Comment by unhammer** [comment]
Viss det er akkurat i det steget, så er det kanskje ein bug i hfst-substitute? `hfst-substitute -f a -t 0:b` burde jo gjera om `a:a -:- a:a` til `0:b -:- 0:b`, ikkje bytta om på rekkefølga eller slå saman ting. 

Kanskje grunnen er at minusteiknet er delt opp i to symbolpar:
```
@_EPSILON_SYMBOL_@:-
@_EPSILON_SYMBOL_@:@_EPSILON_SYMBOL_@
@_EPSILON_SYMBOL_@:@PMATCH_BACKTRACK@
@_EPSILON_SYMBOL_@:@PMATCH_INPUT_MARK@
@_EPSILON_SYMBOL_@:@_EPSILON_SYMBOL_@
-:@_EPSILON_SYMBOL_@
@_EPSILON_SYMBOL_@:@_EPSILON_SYMBOL_@
@_EPSILON_SYMBOL_@:@PMATCH_BACKTRACK@
@_EPSILON_SYMBOL_@:@PMATCH_INPUT_MARK@
@_EPSILON_SYMBOL_@:@_EPSILON_SYMBOL_@
```
på venstresida er det korrekt her (minus i midten), mens på høgresida har me minus først og berre epsilons i midten.

**Comment by snomos** [comment]
Problemet har ingen ting med ä/æ å gjera, det er bindestrekssamansetjingar som ikkje går gjennom, både dynamiske og leksikalske.
