### ISSUE TITLE
make check sier at gramchck-yaml failer selv om den ikke gjør det

### ISSUE THREAD

**Issue by ilm024** [giellalt/lang-smj#19]
/Library/Developer/CommandLineTools/usr/bin/make  check-TESTS
FAIL: msyn-attr-pred.yaml

gramcheck-test.py tools/grammarcheckers/tests/msyn-attr-pred.yaml 

Total passes: 11, Total fails: 0, Total: 11
True positive: 7
True negative: 4
False positive 1: 0
False positive 2: 0
False negative 1: 0
False negative 2: 0
Precision: 100.0%
Recall: 100.0%
F₁ score: 100.0%

**Comment by snomos** [comment]
Kva er status her? Eg trur @albbas har fiksa dette, stemmer det?

**Comment by albbas** [comment]
Ble lukket med giellalt/giella-core@2fb86822e45551e884a3856923817f6589e099d4
