### ISSUE TITLE
Gramchecker klarer ikke å foreslå rett form, kanskje pga Area/NO-tag?

### ISSUE THREAD

**Issue by ilm024** [giellalt/lang-smj#20]
```
: 
"<gænna>"
	"guhti" Area/NO Pron Sem/Hum <smj> <smj> Rel Sg Ine <W:0.0> SELECT:2898 SUBSTITUTE:4065 SUBSTITUTE:4064 &msyn-congr-gænna-gejn SUBSTITUTE:1459 ADD:2062:msyn-congr-gænna-gejn
msyn-congr-gænna-gejn
	"guhti" Area/NO Pron Sem/Hum <smj> <smj> Rel Pl Ine <W:0.0> SELECT:2898 SUBSTITUTE:4065 SUBSTITUTE:4064 &SUGGEST SUBSTITUTE:1459 ADD:2062:msyn-congr-gænna-gejn COPY:2064:msyn-congr-gænna-gejn
guhti+Area/NO+Pron+Rel+Pl+Ine	?
;	"guhti" Area/NO Pron Interr Sg Ine <W:0.0> SELECT:2898
: 
```
Gramchecker klarer ikke å foreslå rett form. Kanskje pga `Area/NO` tag?

hdsmj:
```
guhti+Pron+Rel+Pl+Ine
guhti+Pron+Rel+Pl+Ine	gejn	0,000000
guhti+Pron+Rel+Pl+Ine	gejna	0,000000
```
Forstår ikke hvorfor `Area/NO` dukker opp her, da det ikke er forskjellige SE/NO former. For `guhti+Pron+Rel+Sg+Ine`, er det to former, "_gänna_" og "_gænna_", men det bure vel ikke påvirke noe her.

**Comment by snomos** [comment]
Om eg forstår det rett, så er utgangspunktet at det er brukt ei feil form _gænna_ (ev. _gänna_), som skal rettast til _gejn_/_gejna_. Fordi ordet som er feil inneheld _æ/ä_, så blir det heilt obligatorisk tagga som `Area/NO`, og det er det som hindrar genereringa av den rette ordforma - som ikkje inneheld _æ/ä_, og difor heller ikkje skal ha ein `Area/xx`-tagg.

Den enklaste måten å løysa dette på no trur eg er å fjerna `Area/xx`-taggen med CG-reglar.

**Comment by ilm024** [comment]
Smart! 

"<gænna>"
	"guhti" Area/NO Pron Sem/Hum <smj> <smj> Rel Sg Ine <W:0.0> SELECT:2898 SUBSTITUTE:4065 SUBSTITUTE:4064 &msyn-congr-gænna-gejn SUBSTITUTE:1459 ADD:2062:msyn-congr-gænna-gejn
msyn-congr-gænna-gejn
	"guhti" Pron Sem/Hum <smj> <smj> Rel Pl Ine <W:0.0> SELECT:2898 SUBSTITUTE:4065 SUBSTITUTE:4064 &SUGGEST SUBSTITUTE:1459 ADD:2062:msyn-congr-gænna-gejn COPY:2064:msyn-congr-gænna-gejn
guhti+Pron+Rel+Pl+Ine	gejn,gejna
;	"guhti" Area/NO Pron Interr Sg Ine <W:0.0> SELECT:2898

**Comment by ilm024** [comment]
Jeg tar bort Area-tagger med cg-reglene, men dette er jo ingen lur løsning på sikt. Da må det nemlig legges til manuelt i de fleste regler...

**Comment by snomos** [comment]
Om ein ser på matrisa av analyse og generator i høve til om det finst Area-taggar, så ser det slik ut:

| Input | Analysator | Generator |
| ----- |:----------:|:-----------:|
| Med Area |  X  | ± |
| Utan Area |  X | - |

Area-taggar er valfrie i generatoren. Så så lenge det finst ein Area-tagg i analysen, går det bra å generera både med og utan Area-taggar.

**Comment by snomos** [comment]
Ei robust løysing vil vera å leggja til valfrie Area-taggar av begge slag *der slike ikkje finst frå før*. Area-taggane står alltid før POS-taggen, så det burde vera ganske rett fram å skriva ein regex som legg til slike før POS om det ikkje finst.

Det betyr at for slike ord som har area-taggar vil det fungera som no, og berre den area-spesifikke varianten vil bli generert. For alle andre ord vil dei kunna genererast både med og utan area-taggar, og uansett kva for area-tagg det er. Det burde løysa slike problem over heile fjøla, utan å måtta skriva om CG-reglane.

**Comment by snomos** [comment]
No er det lagt inn. Dvs at no kan alle ord genererast med Area-taggar, eller utan. For ord som ikkje er spesifikke for eit område, går begge (i prinsippet alle) Area-taggar, for Area-spesifikke ord/former går berre den relevante.

Dette gjer generatoren meir robust, og det finst ingen grunn lenger til å laga CG-reglar som fjernar Area-taggar. Både med og utan Area-tagg går, uansett 🙂
