### ISSUE TITLE
Ugyldige stier i smj.zcheck stopper make check i tools/grammarchecker

### ISSUE THREAD

**Issue by albbas** [giellalt/lang-smj#24]
```
lang-smj/tools/grammarcheckers on  main 
❯ make check
```

Gir svaret:
```
Making check in filters
make[1]: Nothing to be done for `check'.
Making check in .
/Library/Developer/CommandLineTools/usr/bin/make  check-local
echo | /usr/local/bin/divvun-checker -a smj.zcheck
{"errs":[],"text":""}
```

Som man ser ovenfor, når man bare kjører divvun-checker på arkivet får man ikke kræsj, men for testene i `tests`, så fører dette til kræsj. I de kræsjene brukes pythonversjonen av divvun-checker.

``` 
Making check in tests
/Library/Developer/CommandLineTools/usr/bin/make  check-TESTS
libc++abi: terminating due to uncaught exception of type std::runtime_error: libdivvun: ERROR: Couldn't find ../../src/cg3/valency.cg3 in archive
/bin/sh: line 1: 74904 Abort trap: 6           "/Users/bga001/repos/giellalt/lang-smj/./../giella-core/scripts/gramcheck-test.py" -q -s ../smj.zcheck ${dir}$tst
XFAIL: DEV-lex-oahpasmuvvat-oahpastuvvat-FAIL.yaml
libc++abi: terminating due to uncaught exception of type std::runtime_error: libdivvun: ERROR: Couldn't find ../../src/cg3/valency.cg3 in archive
/bin/sh: line 1: 74909 Abort trap: 6           "/Users/bga001/repos/giellalt/lang-smj/./../giella-core/scripts/gramcheck-test.py" -q -s ../smj.zcheck ${dir}$tst
```
Jeg kan alltids fikse skriptet gramcheck-test.py, men om man kjører

`echo | divvun-checker -a tools/grammarcheckers/smj.zcheck --variant smjgram-dev` får man svaret: `libdivvun: ERROR: Couldn't find ../../src/cg3/valency.cg3 in archive`, så man kan like gjerne fikse byggeprosessen

Den delen av `pipespec.xml` i smj.zcheck som fører til denne feilen er:
```xml
  <pipeline name="smjgram-dev"
            language="smj"
            type="Grammar error, dev (source) version">
    <tokenize><tokenizer n="tokeniser-gramcheck-gt-desc.pmhfst"/></tokenize>
    <blanktag>
      <blanktagger n="analyser-gt-whitespace.hfst"/>
    </blanktag>
    <cg><grammar n="../../src/cg3/valency.cg3"/></cg>
    <cg><grammar n="../../tools/tokenisers/mwe-dis.cg3"/></cg>
    <mwesplit/>
    <cgspell>
      <lexicon n="acceptor.default.hfst"/>
      <errmodel n="errmodel.default.hfst"/>
    </cgspell>
    <cg><grammar n="valency-postspell.cg3"/></cg>
    <cg><grammar n="./grc-disambiguator.cg3"/></cg>
    <cg><grammar n="./spellchecker.cg3"/></cg>
    <cg><grammar n="after-speller-disambiguator.cg3"/></cg>
    <cg><grammar n="./grammarchecker.cg3"/></cg>
    <suggest>
      <generator n="generator-gramcheck-gt-norm.hfstol"/>
      <messages n="errors.xml"/>
    </suggest>
  </pipeline>
```

**Comment by snomos** [comment]
Dette er ein feil pga ei misforståing. `smjgram-dev` har aldri vore meint å køyrast på denne måten, heile poenget med han er å kunna køyra grammatikkontrollen utan rekompilering (typisk med uike skript i `modes/`), difor peiker pipelinestiene til kjeldefilene (bortsett frå dei som alltid er genererte). Det er altså "feil" med vilje.

`make check` burde I staden nytta pipeline `smjgram`, som er identisk med `smjgram-dev`, bortsett frå at han viser til dei ferdigkompilerte filene, og derfor vil fungera i alle samanhengar der ein ventar seg at `make check` skal fungera.

Eller sagt på ein annan måte: `-dev` i `smjgram-dev` skal tolkast som "developer" (altså personen), og ikkje som "developing" (prosessen). Det er ein pipeline som er meint for menneske, ikkje maskin 🙂

**Comment by albbas** [comment]
Greina [gram-test](giellalt/giella-core/tree/gram-test) i giella-core har en mulig løsning på dette problemet

**Comment by snomos** [comment]
Denne saka er vel løyst no, @albbas ?

**Comment by albbas** [comment]
Ja
