### ISSUE TITLE
make check sier at gramcheck-yamltester failer selv om den ikke gjør det, DEL 2

### ISSUE THREAD

**Issue by ilm024** [giellalt/lang-smj#25]
FAIL: DEV-syn-number_congruence-subj-verb-PASS.yaml

men når jeg kjører "gramcheck-test.py tools/grammarcheckers/tests/DEV-syn-number_congruence-subj-verb-PASS.yaml"
er resultatet

Total passes: 41, Total fails: 0, Total: 41
True positive: 18
True negative: 23
False positive 1: 0
False positive 2: 0
False negative 1: 0
False negative 2: 0
Precision: 100.0%
Recall: 100.0%
F₁ score: 100.0%

echo $? 
0

Tidliger har jeg gjort buggen https://github.com/giellalt/lang-smj/issues/19, men det er noe annet som er feil nå (sier Børre)

**Comment by albbas** [comment]
Løsningen ser ut til å være å oppgradere giella-core.

Denne feilen ser ut til å være fikset i [giellalt/giella-core#f2f54a0b859f555b2eb52766c42288419e015d89](https://github.com/giellalt/giella-core/commit/f2f54a0b859f555b2eb52766c42288419e015d89). Med denne committen av giella-core får jeg:
`PASS: DEV-syn-number_congruence-subj-verb-PASS.yaml`
får jeg kjører `make check`, og den testen failer når jeg kjører testen med en tidligere commit av giella-core.
