### ISSUE TITLE
Grammatikkkontroll retter midt i et ord

### ISSUE THREAD

**Issue by ilm024** [giellalt/lang-smj#27]
Grammatikkkontroll retter midt i et ord, se to vedlagte bilder. 

![Skjermbilde 2023-05-16 kl  14 30 16](https://github.com/giellalt/lang-smj/assets/65161699/6013699c-d69f-4ccc-8956-94612fa57d2b)

<img width="297" alt="Skjermbilde 2023-08-18 kl  15 09 58" src="https://github.com/giellalt/lang-smj/assets/65161699/70b6c298-e09a-468e-ad2b-626174051b4a">

**Comment by snomos** [comment]
Dette ser ut til å vera same feil som alt er registrert for nordsamisk: https://github.com/divvun/divvun-gramcheck-web/issues/52

**Comment by snomos** [comment]
Hadde vore fint med hele teksten (i det minste eit heilt avsnitt) for å reprodusera feilen, ev stadfesta at feilen er løyst 🙂
