### ISSUE TITLE
Spellchecker as part of grammarchecker sucks

### ISSUE THREAD

**Issue by ilm024** [giellalt/lang-smj#28]
![Skjermbilde 2023-08-25 kl  13 33 31](https://github.com/giellalt/lang-smj/assets/65161699/8388bd9a-874a-4f93-9454-ab1a81469590)
![Skjermbilde 2023-08-25 kl  13 32 04](https://github.com/giellalt/lang-smj/assets/65161699/6edf6729-91c5-43f7-be47-21931406256c)

These two words are both correctly spelled.

**Comment by snomos** [comment]
Heile setninga, @ilm024 ? Det er vanskeleg å testa med ufullstendige data 🙂

**Comment by ilm024** [comment]
Iehtjama bargon álgijma 29 500 lemmáj (substantijvaj, adjektijvaj ja verbaj) nuorttasáme-dáro báhkogirjen.

**Comment by ilm024** [comment]
Pivotmetåvdå baktu li 40% nuorttasámegielbágojs oadtjum julevsáme jårggålusáv, dájs ælla gal divna buore gå visses bágo máhtti oadtjot moadda sierra jårggålusá ja daj gaskan li aj boastojårggålusá gå pivotmetåvddå buvtat báhkopárajt ma e duodaj gávnnu gielaj gaskan.

**Comment by snomos** [comment]
Dette ser ikkje ut til å vera eit problem lenger. Med teksten:

> pivotmetåvddå buvtat báhkopárajt
> 
> ja verbaj)

i eit Word-dokument, får eg berre markering på *pivotmetåvddå*. Det ser sli, ut hjå meg:

<img width="985" alt="Skjermbilde 2023-10-23 kl  10 35 21" src="https://github.com/giellalt/lang-smj/assets/1255285/a47c5d0a-2ec1-44eb-b366-f4f2e58755b9">

Eg avsluttar saka. Gjenopne med meir data om det framleis er problem.

**Comment by snomos** [comment]
Med heile setninga får eg same problem, eg gjenopnar.

**Comment by snomos** [comment]
> Pivotmetåvdå baktu li 40% nuorttasámegielbágojs oadtjum julevsáme jårggålusáv, dájs ælla gal divna buore gå visses bágo máhtti oadtjot moadda sierra jårggålusá ja daj gaskan li aj boastojårggålusá gå pivotmetåvddå buvtat báhkopárajt ma e duodaj gávnnu gielaj gaskan.

Det er same sak her som i det førre dømet. Morfologisk analyse:

```
"<buvtat>"
	"buvta" N Err/Orth Sem/Obj Sg Acc PxSg2 <W:0.0>
	"buvta" N Err/Orth Sem/Obj Sg Gen PxSg2 <W:0.0>
	"buvta" N Sem/Obj Sg Nom PxSg2 <W:0.0>
	"buvtadit" V TV Gram/3syll Ind Prs Err/Orth Sg3 <W:0.0>
	"buvtadit" V TV Gram/3syll Ind Prs Sg3 <W:0.0>
```

Og så blir ein `Err/Orth`-analyse vald istf den rette:

```
"<buvtat>"
	"buvta" N <smj> <smj> Sem/Obj Sg Gen PxSg2 <W:0.0> &typo &SUGGEST #31->31
buvta+N+Sg+Gen+PxSg2	buktagat,buktagit
```

**Comment by snomos** [comment]
Eg sender denne saka til dykk, @ilm024 og @lynnda-hill 🙂

**Comment by lynnda-hill** [comment]
fiksa begge, bare send flere eksempler, det er artig

**Comment by ilm024** [comment]
Divvoma gållekorpusin vuojnná jut julevsámegielaga rahtji tjállemgielajn, ja jut a/á mierkkim la stuorámus ortografijjalasj rahtjamus. Gå vuostasjgielaga rahtji åsijn tjállemgielas de la luondulasj jáhkket jut dat oasse gielas mij mierkkiduvvá tjállemgielan, ij boade åvddån sijá njálmálasj gielan. Báddima ma doajmmi dáhtán dán tjállusij vuosedi jut julevsámegielaga divtesuorgijn tjielggasit ieredi a/á-jienajt njálmálasj gielan.

Julevsámegiella Divtasvuonan la ælládahteduvvam ja nuppátgielaga li ájnas ja stuor oasse giellasebrudagás. Nievres tjielggidusá a/á-jienajs máhtti lájddit nuppátgielagijt tsieggitjit boasto dádjadusáv julevsámegielas ja dakkir dilen soajtti giellarievddama jåhtelappot dáhpáduvvat. Dát tjálos la åvdemusát vuosedam jut a/á-jienaj guhkkudahka l komplæksa ja jut kvalitiehtta bierri ienebut dættoduvvat grammatihkajn ja tjállembagádusájn. Ienep guoradallama dárbahuvvi gal jus galggá sihkarasstet jut ådåságastiddje oadtju rievtes dádjadusáv a/á-jienajs ja jus galggá viehkedit vuostasjgielagijt gå galggi julevsámegielav tjállet.

**Comment by snomos** [comment]
Problemet er disambigueringa. Her er det som kjem frå den morfologiske analysen:

```
"<jut>"
	"jut" CS <W:0.0>
: 
"<dat>"
	"dat" Pron Dem Sg Ela Attr <W:0.0>
	"dat" Pron Dem Sg Nom <W:0.0>
	"dat" Pron Dem Sg Par <W:0.0>
: 
"<oasse>"
	"oasse" N Err/Orth Sem/Part Pl Nom <W:0.0>
	"oasse" N Err/Orth Sem/Part Sg Gen <W:0.0>
	"oasse" N Sem/Part Sg Nom <W:0.0>
: 
"<gielas>"
	"gielas" N Sem/Plc Sg Nom <W:0.0>
	"giella" N Sem/Lang_Tool-catch Sg Acc PxSg3 <W:0.0>
	"giella" N Sem/Lang_Tool-catch Sg Ela <W:0.0>
	"giella" N Sem/Lang_Tool-catch Sg Gen PxSg3 <W:0.0>
	"giellat" Ex/V TV Der/st V Gram/3syll Ind Prs Err/Orth Sg3 <W:0.0>
	"giellat" Ex/V TV Der/st V Gram/3syll Ind Prs Sg3 <W:0.0>
: 
"<mij>"
	"mij" Pron Interr Sg Nom <W:0.0>
	"mij" Pron Rel Sg Nom <W:0.0>
	"mån" Pron Pers Pl1 Nom <W:0.0>
: 
"<mierkkiduvvá>"
	"mierkkit" Ex/V Ex/TV Der/PassL V IV Ind Prs Sg3 <W:0.0>
: 
"<tjállemgielan>"
	"gielas" N Sem/Plc Ess <W:0.0>
		"tjállem" N Sem/Dummytag Gram/NomAct Cmp/SgNom Cmp <W:0.0>
	"giella" N Sem/Lang_Tool-catch Sg Ine <W:0.0>
		"tjállem" N Sem/Dummytag Gram/NomAct Cmp/SgNom Cmp <W:0.0>
	"giellat" Ex/V TV Der/NomInstr N Sg Nom <W:0.0>
		"tjállem" N Sem/Dummytag Gram/NomAct Cmp/SgNom Cmp <W:0.0>
	"tjállemgiella" N Sem/Lang Sg Ine <W:0.0>
	"gielas" N Sem/Plc Ess <W:0.0>
		"tjállet" Ex/V TV Der/NomAct N Cmp/SgNom Cmp <W:0.0>
	"giella" N Sem/Lang_Tool-catch Sg Ine <W:0.0>
		"tjállet" Ex/V TV Der/NomAct N Cmp/SgNom Cmp <W:0.0>
	"giellat" Ex/V TV Der/NomInstr N Sg Nom <W:0.0>
		"tjállet" Ex/V TV Der/NomAct N Cmp/SgNom Cmp <W:0.0>
"<,>"
	"," CLB <W:0.0>
```

Og her er resultatet rett før forslag osb blir generert:

```
"<oasse>"
	"oasse" N <smj> <smj> Sem/Part Sg Gen <W:0.0> SELECT:3329 SUBSTITUTE:4182 &typo &SUGGEST ADD:8:Err/Orth COPY:9:Err/Orth SUBSTITUTE:4181
;	"oasse" N <smj> Err/Orth Sem/Part Sg Gen <W:0.0> SELECT:3329 SUBSTITUTE:4182 &typo ADD:8:Err/Orth COPY:9:Err/Orth REMOVE:4174:errsub
;	"oasse" N Err/Orth Sem/Part Pl Nom <W:0.0> SELECT:3329
;	"oasse" N Sem/Part Sg Nom <W:0.0> SELECT:3329
```

Som de ser @ilm024 og @lynnda-hill har disambigueringa valt feil analyse. Så dette har ikkje noko med stavekontrollen å gjera.

Eg lukkar denne meldinga på nytt. Det er betre å laga nye meldingar for nye feil, så kan ein endra tittelen på meldinga i samsvar med det ein kjem fram til at feilen faktisk handlar om 🙂
