### ISSUE TITLE
Sjekk oppføringar med kløyvd lemma i

### ISSUE THREAD

**Issue by snomos** [giellalt/lang-smj#3]
Det finst oppslag i smj med dette mønsteret:

```
+Err/MissingSpace+Sg+Gen+dagi+Po:bu%>∑#dagi K
+N+Der2+Der/Dimin+N+Err/MissingSpace+Pl+Gen+dagá+Po:»ttja%>j∑#dagá K
```

Dette er ikkje bra - lemma bør vera samanhangande utan taggar i midten. Særleg for grammatikkontrollen/`hfst-tokenise`er det problematisk med slike kløyvde lemma. Lene meldte frå om problemet.

**Comment by ilm024** [comment]
LEXICON DAGI_SINGULAR !!= @CODE@ Earlier we generated "bijladagi" and bijlajdagi as abbessiv. This has been fixed, but to be able to analyse what we earlier generated, we needed this lexicon. Only singular. Gives Err/tag to "bijladagi" and makes correct "bijla dagi".


+Sg+Gen@P.Pmatch.Loc@% dagi+Po:%>@P.Pmatch.Loc@% dagi                             K   ; !Correct bijla dagi
+Sg+Gen@P.Pmatch.Loc@% dagá+Po:%>@P.Pmatch.Loc@% dagá                             K   ; !Correct bijla dagi
+Err/Orth+Sg+Gen@P.Pmatch.Loc@% dagá+Po:%>@P.Pmatch.Loc@% tagá                    K   ; !Correct bijla dagi
																			     
+Sg+Gen+Err/MissingSpace@P.Pmatch.Loc@% dagi+Po:%>@P.Pmatch.Loc@∑#dagi            K   ; !Wrong bijladagi
+Sg+Gen+Err/MissingSpace@P.Pmatch.Loc@% dagá+Po:%>@P.Pmatch.Loc@∑#dagá            K   ; !Wrong bijladagi
+Err/Orth+Sg+Gen+Err/MissingSpace@P.Pmatch.Loc@% dagá+Po:%>@P.Pmatch.Loc@∑#tagá   K   ; !Wrong bijladagi


LEXICON DAGI_PLURAL !!= @CODE@ Earlier we gave generated "bijladagi" and bijlajdagi as abbessiv. This has been fixed, but to be able to analyse what we earlier generated, we needed this lexicon. Only plural. Gives Err/tag to "bijlajdagi" and makes correct "bijlaj dagi".

+Pl+Gen@P.Pmatch.Loc@% dagi+Po:%>j@P.Pmatch.Loc@% dagi                            K   ; !Correct bijlaj dagi
+Pl+Gen@P.Pmatch.Loc@% dagá+Po:%>j@P.Pmatch.Loc@% dagá                            K   ; !Correct bijlaj dagi
+Err/Orth+Pl+Gen@P.Pmatch.Loc@% dagá+Po:%>j@P.Pmatch.Loc@% tagá                   K   ; !Correct bijlaj dagi

+Pl+Gen+Err/MissingSpace@P.Pmatch.Loc@% dagi+Po:%>j@P.Pmatch.Loc@∑#dagi           K   ; !Wrong bijlajdagi
+Pl+Gen+Err/MissingSpace@P.Pmatch.Loc@% dagá+Po:%>j@P.Pmatch.Loc@∑#dagá           K   ; !Wrong bijlajdagi
+Err/Orth+Pl+Gen+Err/MissingSpace@P.Pmatch.Loc@% dagá+Po:%>j@P.Pmatch.Loc@∑#tagá  K   ; !Wrong bijlajdagi
