### ISSUE TITLE
TTS: 'Dr.' blir segmentert som 'dr'+setningsgrense i starten av ei setning

### ISSUE THREAD

**Issue by snomos** [giellalt/lang-smj#33]
Jf denne setninga:

> Dr. Phil Gudmun Hatt tjállá jagen 1918 ietjas dutkamin ahte hæhttuji liehket bivddoulmutja gudi vuostak tsieggigåhtin ælojt.

Med kommandoen:
```sh
echo 'Dr. Phil Gudmun Hatt tjállá jagen 1918 ietjas dutkamin ahte \
hæhttuji liehket bivddoulmutja gudi vuostak tsieggigåhtin ælojt.' | \
./tools/tts/modes/smj-normaliser.mode
```
kjem ho ut slik:

```
"<Dr>"
	"dr" N Sem/Hum ABBR Gram/TAbbr Sg Nom <W:0.0> @HNOUN #1->0
	"dr" N Sem/Hum ABBR Gram/TAbbr Sg Nom "dr"MIDTAPE <W:0.0> @HNOUN #1->0
	"dr" N Sem/Hum ABBR Gram/TAbbr Pl Nom "dr"MIDTAPE <W:0.0> @HNOUN #1->0
"<.>"
	"." CLB <W:0.0> #2->1
	"." CLB "."MIDTAPE <W:0.0> #2->1
: 

"<Phil>"
	"Phil" OLang/UND N Prop Sem/Sur Sg Nom "Phil>"MIDTAPE <W:0.0> @SUBJ> #1->4
: 
"<Gudmun>"
	"Gudmun" ? @X #2->0
: 
"<Hatt>"
	"Hatt" OLang/UND N Prop Sem/Sur Sg Nom "Hatt>"MIDTAPE <W:0.0> @SUBJ> #3->4
: 
"<tjállá>"
	"tjállet" <mv> V <RE-Ill-Ani><TH-Acc-*Ani> <RE-Ill-Ani> TV Ind Prs Sg3 "tjálle>Y2"MIDTAPE <W:0.0> @FMV #4->0
	"tjállát" <mv> V TV Ind Prs Sg3 "tjálºlá>"MIDTAPE <W:0.0> @FMV #4->0
: 
```

som sjølvsagt er feil. Det er i MWE-disambigueringa det går gale.

Kan de sjå på det, @lynnda-hill og @ilm024 ?

**Comment by lynnda-hill** [comment]
This cannot be fixed by CG because we only get the option CLB and not PUNCT
"<.>"
	"." CLB <W:0.0> #2->1
	"." CLB "."MIDTAPE <W:0.0> #2->1

**Comment by lynnda-hill** [comment]
I did a fix in mwe-dis.cg3 and now tokenization works as it should. We do not get "Attr", but that needs to be fixed in another disambiguation file.

"<Dr.>"
        "dr" N Sem/Hum ABBR Gram/TAbbr Sg Acc "dr."MIDTAPE <W:0.0> @OBJ> #1->5
        "dr" N Sem/Hum ABBR Gram/TAbbr Sg Acc <W:0.0> @OBJ> #1->5
: 
"<Phil>"
        "Phil" OLang/UND N Prop Sem/Sur Sg Nom "Phil>"MIDTAPE <W:0.0> @SUBJ> #2->5
: 
"<Gudmun>"
        "Gudmun" ? @X #3->0
: 
"<Hatt>"
        "Hatt" OLang/UND N Prop Sem/Sur Sg Nom "Hatt>"MIDTAPE <W:0.0> @SUBJ> #4->5

**Comment by snomos** [comment]
Det ser bra ut, eg får same resultat. Eg avsluttar saka.
