### ISSUE TITLE
giella-smj not built since feb 2022

### ISSUE THREAD

**Issue by unhammer** [giellalt/lang-smj#41]
sist pakke er frå
https://github.com/giellalt/lang-smj/commit/85bb4b27

https://apertium.projectjj.com/apt/logs/giella-smj/sid-amd64.log
seier 
```
configure.ac:35: installing 'build-aux/install-sh'
configure.ac:35: installing 'build-aux/missing'
automake: error: cannot open < ../giella-core/am-shared/docs-dir-include.am: No such file or directory
autoreconf: error: automake failed with exit status: 1
dh_autoreconf: error: autoreconf -f -i returned exit code 1
make: *** [debian/rules:9: binary] Error 255
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
```

**Comment by snomos** [comment]
Feilen må vera ein annan:

```sh
ls -l giella-core/am-shared/docs-dir-include.am 
-rw-r--r--  1 smo036  staff  7879 Jan 22 09:58 giella-core/am-shared/docs-dir-include.am
```

og bygginga fungerer i GH-CI-bygginga (med Taskcluster), i alle fall langt forbi dette punktet.

**Comment by unhammer** [comment]
@TinoDidriksen is this because scripts use giella-core from package but automake seems to use a relative path?

**Comment by TinoDidriksen** [comment]
Probably, though I have a rewrite helper that should have fixed such paths. Maybe I need to use bundling for all giella builds - easy enough to do, but that is not how building should work.

**Comment by TinoDidriksen** [comment]
Finally built now that all deps built, but required ignoring tests for smj as well. `No rule to make target 'DEV-msyn-nom-nom-FAIL.yaml', needed by 'check-TESTS'.`
