### ISSUE TITLE
transcriptor-numbers-digit2text.lexc dekkjer ikkje ordenstal

### ISSUE THREAD

**Issue by snomos** [giellalt/lang-smj#8]
Dette hindrar normalisering/konvertering til tekst av ting som:

```sh
cd lang-smj
echo Bårggemáno 9. Biejvve le AN:a rijkajgasskasasj álggoálmmukbiejvve. \
  | tools/tts/modes/trace-smj-analyser.mode
```

Full sti er: `src/transcriptions/transcriptor-numbers-digit2text.lexc `.

For at testen over skal fungera må ein ha konfigurert for tts:

```sh
./configure --enable-tokenisers --enable-phonetic --enable-tts
```

For nordsamisk er dette på plass, sjå der for korleis det kan gjerast.

**Comment by ilm024** [comment]
Fixed:

uit-mac-219:lang-smj ilm024$ echo  '1000.' | hfst-lookup -q src/transcriptions/transcriptor-numbers-digit2text.filtered.lookup.hfstol
1000.	tuvsánat	0,000000

uit-mac-219:lang-smj ilm024$ echo  '9111.' | hfst-lookup -q src/transcriptions/transcriptor-numbers-digit2text.filtered.lookup.hfstol
9111.	aktsetuvsántjuohtelågenanvuostasj	0,000000
9111.	aktsetuvsántjuotlågenanvuostasj	0,000000

uit-mac-219:lang-smj ilm024$ echo  '9.' | hfst-lookup -q src/transcriptions/transcriptor-numbers-digit2text.filtered.lookup.hfstol
9.	avtsát	0,000000
